djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plant-sharing/', include('ps.urls', namespace='ps')),
    path('users/', include('users.urls', namespace='users')),
]

ps/urls.py
from django.urls import path
from . import views
from django.conf import settings

app_name = 'plant-sharing'
assert isinstance(settings.STATIC_URL, object)
urlpatterns = [
                path('', views.landing_page, name='landing_page'),
                path('home', views.plant_list_search, name='homepage'),
                path('plants/plant', views.plant_add, name='plant_add'),
                path('plants/plant/<int:plant_id>', views.plant_edit, name='plant_edit'),
                path('plants/plant/<int:plant_id>/details', views.plant_details, name='plant_details'),
                path('plants', views.plant_list, name='my_listings'),
                path('messages', views.my_messages, name='my_messages'),
                path('results', views.global_search_results, name='global_search_results'),
                path('plants/plant/delete', views.plant_delete, name='delete_plant_listing'),
                path('plants/plant/all', views.full_list, name='all_plant_listings'),
                path('plants/plant/<int:plant_id>/save', views.save_details, name='plant_data_save'),
                path('plants/<int:plant_id>/comment', views.post_comments, name='post_comment'),
                path('comment/<int:comment_id>', views.edit_comment, name='edit_comment'),
                path('comment/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
              ]

users/urls.py
from django.urls import path
from . import views
from django.conf import settings

app_name = 'users'
assert isinstance(settings.STATIC_URL, object)
urlpatterns = [
                path('register', views.register, name='register'),
                path('profile/<str:username>', views.profile, name='profile'),
                path('login', views.login_user, name='login'),
                path('logout', views.logout_user, name='logout'),
                path('profile/<str:username>/edit', views.edit_profile, name='editProfile'),
                path('profile/<str:username>/save', views.save, name='save')
              ]

templates/plant-sharing/plants/detailed-view.html
<!-- Detail view
This page displays the data of a particular plant record and gives option of an edit button to go to the editable form page.
 -->
{% extends "plant-sharing/base.html" %}
{% load humanize %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <link rel="stylesheet" href="{% static "css/search-plants.css" %}">
    <link rel="stylesheet" href="{% static "css/add-plants.css" %}">
    <link rel="stylesheet" href="{% static "css/my-listings.css" %}">
{% endblock %}

{% block extrascripts %}
    <script src="{% static "js/plantdetails.js" %}"></script>
    <script src="{% static "js/comments.js" %}"></script>
{% endblock %}

{% block primary-navigation %}
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
    <li><a href="#">My Profile</a></li>
    <li><a href="{% url 'users:logout' %}" >Logout</a></li>
{% endblock %}

{% block navigation %}
    <div id="navigation">
        <ul>
            <li>
                <a href="/plant-sharing/home">Search Plants</a>
            </li>
            <li>
                <a href="{% url "ps:my_listings" %}" class="selected">My Listing</a>
            </li>
            <li>
                <a href="/plant-sharing/messages">My Messages</a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div id="my-listings">
        <ul>
            <li><a href="{% url "ps:my_listings" %}">My Listing</a></li>
            <li><a href="{% url "ps:plant_details" plant.id %}" class="selected">View Details</a></li>
            <li><a href="{% url "ps:plant_add" %}"><img src="{% static "media/img/misc/add-button.png" %}" alt=""
                                                        width="30" height="30"></a></li>
        </ul>
        <h3>Below are the plant details:</h3>
        <p>
            Plant Name: {{ plant.name }}<br>
            Description: {{ plant.description }}<br>
            Status: {{ plant.status }}<br>
            Posted by: {{ plant.user.username }}<br>
            Last Updated by: {{ plant.updatedBy }}<br>
            Updated On: {{ plant.lastUpdateOn }}<br>
            Created On: {{ plant.datePosted }}<br>
            Personal Notes: {{ plant.notes }}
        <form action="{% url "ps:my_listings" %}" method="get">
            <button type="submit">Back</button>
            {% if request.session.role == 'admin' or request.session.username == plant.user.username %}
                <button type="submit" formaction="{% url "ps:plant_edit" plant.id %}">Click to edit</button>
            {% endif %}
        </form>
        </p>
    </div>

    <div id="comment-section">
        <h3>Comment Section</h3>
        <form class="new-comment" action="{% url "ps:post_comment" plant.id %}" method="get">
            <textarea id="newComment" value="Comment" minlength="5"></textarea>
            <button type="submit">Post</button>
        </form>
        {% if comments != 'None' %}
            <div id="all-comments">
                {% for comment in comments %}
                    <div class="each-comment" data-comment-id="{{  comment.id }}">
                        <a href="{% url "users:profile" comment.postedBy %}">{{  comment.postedBy }}</a> posted {{  comment.lastUpdateOn| naturaltime }}:
                       <div class="comment-text">{{ comment.commentText }}</div>
                        {% if request.session.role == 'admin' or request.session.username == comment.postedBy.username %}
                            <div id="edit-comment">Click to <a data-c-id="{{  comment.id }}" href="{% url "ps:edit_comment" comment.id %}">edit the post</a></div>
                            <div id="delete-comment">Click to <a href="{% url "ps:delete_comment" comment.id %}">delete the post</a></div>
                        {% endif %}
                    </div>
                    {%  empty %}
                    <p>No comments yet.</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/plant-sharing/plants/details.html
<!-- Add view, Edit view, Delete view
This page displays the form in which is used to view, add, edit and delete the plant listing.
       Delete functionality is only visible to logged in user with role: admin in edit view
 -->
{% extends "plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <link rel="stylesheet" href="{% static "css/search-plants.css" %}">
    <link rel="stylesheet" href="{% static "css/add-plants.css" %}">
    <link rel="stylesheet" href="{% static "css/my-listings.css" %}">
{% endblock %}

{% block extrascripts %}
    <script src="{% static "js/plantdetails.js" %}"></script>
{% endblock %}

{% block primary-navigation %}
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
    <li><a href="#">My Profile</a></li>
    <li><a href="{% url 'users:logout' %}">Logout</a></li>
{% endblock %}

{% block navigation %}
    <div id="navigation">
        <ul>
            <li>
                <a href="/plant-sharing/home">Search Plants</a>
            </li>
            <li>
                <a href="{% url "ps:my_listings" %}" class="selected">My Listing</a>
            </li>
            <li>
                <a href="/plant-sharing/messages">My Messages</a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div id="my-listings">
        <ul>
            <li><a href="{% url "ps:my_listings" %}">My Listing</a></li>
            <li><a href="/plant-sharing/plants/plant" class="selected">{% if plant.id %}Edit{% else %}Add{% endif %}
                plant</a></li>
            <li><a href="/plant-sharing/plants/plant"><img src="{% static "media/img/misc/add-button.png" %}" alt=""
                                                           width="30" height="30"></a></li>
        </ul>
        <h3>Please enter the plant details below you want to list:</h3>
        <p>* = required</p>
        <form action="{% url "ps:plant_add" %}" class="addOrEditItem" method="POST">
            {% csrf_token %}
            <label for="pname">Plant name:*</label>
            <input type="text" id="pname" name="pname" required maxlength="20" minlength="4" value="{{ plant.name }}">
            <label for="image">Upload Image:*</label>
            <input type="file" id="image" name="filename">
            <br>
            <label for="description">Description:*</label>
            <textarea id="description" name="description" minlength="4" required>{{ plant.description }}</textarea>
            <label for="notes">Notes:</label>
            <textarea id="notes" name="notes" minlength="4" value="{{ plant.notes }}"></textarea>
            <br>
            <label>Location:</label>
            <a href="#"><img alt="" src="{% static  "media/img/misc/location-icon.jpeg" %}" width="30" height="30"></a>
            <br>

            {% if plant.id %}
                <label for="status">Status:*</label>
                <select name="status" id="status">
                    {% for status in statuses %}
                        <option value="{{ status }}"
                                {% if plant.status == status %}selected {% endif %}>{{ status }}</option>
                    {% endfor %}
                </select>
            {% endif %}
            <br>
            <input type="hidden" id="plantId" name="plantId" value="{{ plant.id }}">
            <input type="submit" value="Submit">
        </form>
        {% if request.session.role == 'admin' and plant.id %}
            <form class="deleteItem" data-action-url="{% url "ps:delete_plant_listing" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" id="plant_Id" name="plant_Id" value="{{ plant.id }}">
                <input type="submit" name="deleteItem" value="Remove Item"/>
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block ad3 %}
    <a id="ad3" href="#">
        <img src="{% static "media/img/ads/Sample-Sidebar-Ad.png" %}" alt="Ad3 picture" width="100" height="60"/>
    </a>
{% endblock %}

templates/plant-sharing/plants/home.html
<!-- This page displays the list of all the plants listed by all the users
 This page will be visible to logged in users with any role. -->
{% extends "plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <link rel="stylesheet" href="{% static "css/search-plants.css" %}">
{% endblock %}
{% block extrascripts %}
    <script src="{% static "js/search.js" %}"></script>
{% endblock %}
{% block global-search %}
    <form id="search-bar" class="global-search" method="GET">
        {% csrf_token %}
        <input type="text" class="globalSearch" placeholder="Search.." size="70">
        <input type="submit" value="Go!">
    </form>
{% endblock %}
{% block primary-navigation %}
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
    <li><a href="{% url 'users:profile' request.session.username %}">My Profile</a></li>
    <li><a href="{% url 'users:logout' %}">Logout</a></li>
{% endblock %}

{% block navigation %}
    <div id="navigation">
        <ul>
            <li>
                <a href="/plant-sharing/home" class="selected">Search Plants</a>
            </li>
            <li>
                <a href="{% url "ps:my_listings" %}">My Listing</a>
            </li>
            <li>
                <a href="/plant-sharing/messages">My Messages</a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div id="search-plants">
        <div id="search-form">
            {% csrf_token %}
            <select name="plant-types" class="plant-types">
                <option class="default">Plant types</option>
                <option value="rose">Red rose</option>
                <option value="mint">Mint</option>
            </select>
            <select name="radius" class="distance-radius">
                <option class="default">Distance Radius</option>
                <option value="rose">2 miles</option>
                <option value="mint">10 miles</option>
            </select>
            <input type="text" class="searchtext" placeholder="What are you looking for?">
            <input type="submit" class="search" value="Search">
        </div>
        <table class="search-table">
            <tr>
                <th>Plant Type</th>
                <th>Plant Image</th>
                <th>Distance</th>
                <th id="desc">Plant Description</th>
                <th>Connect</th>
            </tr>
             {% for plant in plants_list %}
                <tr>
                    <td>{{ plant.name |truncatewords:"100" }}</td>
                    <td><a href="#"><img src="{{ plant.imagePath }}" alt="" width="30" height="30"></a></td>
                    <td>{{ plant.distance }}</td>
                    <td>{{ plant.description |truncatewords:"200" }}</td>
                    <td><a href="{% url "ps:plant_details" plant.id %}"><img
                            src="{% static "media/img/misc/connect-icon.png" %}" alt="Comment" width="30" height="30"></a>
                    </td>
                </tr>
            {% endfor %}
            {% if plants_list.count == 0 %}
                No plants listed yet!
            {% endif %}
        </table>
    </div>
{% endblock %}
{% block ad3 %}
    <a id="ad3" href="#">
        <img src="{% static "media/img/ads/Sample-Sidebar-Ad.png" %}" alt="Ad3 picture" width="100" height="60"/>
    </a>
{% endblock %}
{% block sidebar %}
    {% include "actions/action/feed.html" %}
{% endblock %}

templates/plant-sharing/plants/landing.html
<!-- Home view
This page is the landing page for an anonymous user which displays the login component and the general information about the application. -->
{% extends "plant-sharing/base.html" %}
{% load static %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/anonymous-homepage.css" %}">
{% endblock %}

{% block primary-navigation %}
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
{% endblock %}

{% block content %}
    <div id="purpose-content">
        <h2>Get connected to the fellow plant enthusiasts near you!</h2>
        <p>This application will provide a platform to all the gardening enthusiasts to share the extra plants, saplings
            or cuttings with the fellow enthusiasts near their location or area.
        </p>
        <span>How it will help:</span>
        <ul>
            <li> Provide a platform enabling distribution of free plants to people.</li>
            <li>Socialize and meet like-minded home gardeners.</li>
            <li>Will promote green and lessen pollution/global warming</li>
        </ul>
    </div>
    <div id="login">
        <h2>Sign in to access your account.</h2>
        <form method="POST" action="{% url "users:login" %}">
            {% csrf_token %}
            <input type="text" name="username" required maxlength="45" minlength="4" placeholder="Enter Username">
            <br>
            <input type="password" name="pw" required maxlength="45" minlength="5" placeholder="Enter Password">
            <br>
            <input type="submit" name="submit" value="Login">
            <br>
            New User? <a href="{% url 'users:register' %}">Register here!</a>
            <br>
            <a href="#">Forgot username or password?</a>
        </form>
    </div>
{% endblock %}

templates/plant-sharing/plants/list.html
<!-- List view
This page displays the list of all the plants added by the logged in user and to any user with the admin role. -->
{% extends "plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <link rel="stylesheet" href="{% static "css/my-listings.css" %}">
{% endblock %}

{% block extrascripts %}
    <script src="{% static "js/list.js" %}"></script>
{% endblock %}

{% block primary-navigation %}
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
    <li><a href="#">My Profile</a></li>
    <li><a href="{% url 'users:logout' %}">Logout</a></li>
{% endblock %}

{% block navigation %}
    <div id="navigation">
        <ul>
            <li>
                <a href="/plant-sharing/home">Search Plants</a>
            </li>
            <li>
                <a href="{% url "ps:my_listings" %}" class="selected">My Listing</a>
            </li>
            <li>
                <a href="/plant-sharing/messages">My Messages</a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div id="my-listings" data-edit-url="{% url "ps:plant_edit" 0 %}" data-details-url="{% url "ps:plant_details" 0 %}"
         data-details-img="{% static "media/img/misc/view-icon.jpeg" %}"
         data-edit-img="{% static "media/img/misc/edit-icon.png" %}" data-name-save="{% url "ps:plant_data_save" 0 %}">
        <ul>
            <li><a href="{% url "ps:my_listings" %}" class="selected">My Listing</a></li>
            <li><a href="/plant-sharing/plants/plant">Add plant</a></li>
            <li>
                <a href="/plant-sharing/plants/plant">
                    <img src="{% static "media/img/misc/add-button.png" %}" alt="" width="30" height="30">
                </a>
            </li>
        </ul>
        <table id="myPlantTable">
            <tr>
                <th>Plant Name</th>
                <th>Image</th>
                <th>Description</th>
                <th>Location</th>
                <th>Status</th>
                <th>Edit</th>
                <th>Details</th>
            </tr>

            {% for plant in plants_list %}
                <tr>
                    <td class="editable"
                        data-save-url={% url "ps:plant_data_save" plant.id %}>{{ plant.name |truncatewords:"100" }}</td>
                    <td><a href="#"><img src="{{ plant.imagePath }}" alt="" width="30" height="30"></a></td>
                    <td>{{ plant.description |truncatewords:"200" }}</td>
                    <td>{{ plant.distance }}</td>
                    <td>{{ plant.status }}</td>
                    <td><a href="{% url "ps:plant_edit" plant.id %}"><img
                            src="{% static "media/img/misc/edit-icon.png" %}" alt="Edit" width="30" height="30"></a>
                    </td>
                    <td><a href="{% url "ps:plant_details" plant.id %}"><img
                            src="{% static "media/img/misc/view-icon.jpeg" %}" alt="View" width="30" height="30"></a>
                    </td>
                </tr>
            {% endfor %}
            {% if plants_list.count == 0 %}
                No plants listed yet!
            {% else %}
                <button id="sortByName" data-ajax-url="{% url "ps:all_plant_listings" %}">Sort alphabetically by all
                    Plant Name
                </button>
            {% endif %}

        </table>
        {% if plants_list.count != 0 %}
            <button class="loadData" data-ajax-url="{% url "ps:all_plant_listings" %}">Load All!</button>
        {% endif %}
    </div>

{% endblock %}

{% block ad3 %}
    <a id="ad3" href="#">
        <img src="{% static "media/img/ads/Sample-Sidebar-Ad.png" %}" alt="Ad3 picture" width="100" height="60"/>
    </a>
{% endblock %}

templates/plant-sharing/plants/messages.html
<!-- This page displays the messages of all the plant enthusiasts and the user's reply option visible to the logged in user and to any user with the admin role. -->
{% extends "plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <link rel="stylesheet" href="{% static "css/my-messages.css" %}">
{% endblock %}

{% block primary-navigation %}
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
    <li><a href="#">My Profile</a></li>
    <li><a href="{% url 'users:logout' %}">Logout</a></li>
{% endblock %}

{% block navigation %}
    <div id="navigation">
        <ul>
            <li>
                <a href="/plant-sharing/home">Search Plants</a>
            </li>
            <li>
                <a href="{% url "ps:my_listings" %}">My Listing</a>
            </li>
            <li>
                <a href="/plant-sharing/messages" class="selected">My Messages</a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div id="my-messages">
        <table>
            <tr>
                <th>Prospect Plant taker Name</th>
                <th>Plant Name</th>
                <th>Inquiry</th>
                <th>Reply</th>
            </tr>
            <tr>
                <td>John Cena</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>
            <tr>
                <td>Rahul</td>
                <td>Mint</td>
                <td>Hi There! please share the details of the pickup.</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>Raj</td>
                <td>Rose cutting</td>
                <td>Hi There! do you have white roses?</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>Johnny</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>Seleena</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>John Cena</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>John Cena</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>John Cena</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>John Cena</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

            <tr>
                <td>John Cena</td>
                <td>Rose cutting</td>
                <td>Hi There! let me know when it is available!</td>
                <td><a href="#"><img src="../static/media/img/misc/reply-icon.jpeg" alt="" width="20" height="20"></a>
                </td>
            </tr>

        </table>
    </div>
{% endblock %}

{% block ad3 %}
    <a id="ad3" href="#">
        <img src="{% static "media/img/ads/Sample-Sidebar-Ad.png" %}" alt="Ad3 picture" width="100" height="60"/>
    </a>
{% endblock %}

templates/plant-sharing/plants/search-results.html
<!-- This page displays the list of all the plants listed after processing from the global search from the homepage.
 This page will be visible to logged in users with any role. -->
{% extends "plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <link rel="stylesheet" href="{% static "css/search-plants.css" %}">
{% endblock %}
{% block global-search %}
    <form id="search-bar" class="global-search" method="GET">
        <input type="text" class="globalSearch" placeholder="Search.." size="70">
        <input type="submit" value="Go!">
    </form>
{% endblock %}
{% block extrascripts %}
    <script src="{% static "js/result.js" %}"></script>
{% endblock %}
{% block primary-navigation %}
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
    <li><a href="#">My Profile</a></li>
    <li><a href="{% url 'users:logout' %}">Logout</a></li>
{% endblock %}

{% block navigation %}
    <div id="navigation">
        <ul>
            <li>
                <a href="/plant-sharing/home" class="selected">Search Plants</a>
            </li>
            <li>
                <a href="{% url "ps:my_listings" %}">My Listing</a>
            </li>
            <li>
                <a href="/plant-sharing/messages">My Messages</a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div id="search-plants">
        <table class="search-table">
            <tr>
                <th>Plant Type</th>
                <th>Plant Image</th>
                <th>Distance</th>
                <th id="desc">Plant Description</th>
                <th>Connect</th>
            </tr>
        </table>
    </div>
{% endblock %}
{% block ad3 %}
    <a id="ad3" href="#">
        <img src="{% static "media/img/ads/Sample-Sidebar-Ad.png" %}" alt="Ad3 picture" width="100" height="60"/>
    </a>
{% endblock %}