djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plant-sharing/', include('ps.urls', namespace='ps')),
    path('users/', include('users.urls', namespace='users')),
]

ps/urls.py
from django.urls import path
from . import views
from django.conf import settings

app_name = 'plant-sharing'
assert isinstance(settings.STATIC_URL, object)
urlpatterns = [
                path('', views.landing_page, name='landing_page'),
                path('home', views.plant_list_search, name='homepage'),
                path('plants/plant', views.plant_add, name='plant_add'),
                path('plants/plant/<int:plant_id>', views.plant_edit, name='plant_edit'),
                path('plants/plant/<int:plant_id>/details', views.plant_details, name='plant_details'),
                path('plants', views.plant_list, name='my_listings'),
                path('messages', views.my_messages, name='my_messages'),
                path('results', views.global_search_results, name='global_search_results'),
                path('plants/plant/delete', views.plant_delete, name='delete_plant_listing'),
                path('plants/plant/all', views.full_list, name='all_plant_listings'),
                path('plants/plant/<int:plant_id>/save', views.save_details, name='plant_data_save'),
                path('plants/<int:plant_id>/comment', views.post_comments, name='post_comment'),
                path('comment/<int:comment_id>', views.edit_comment, name='edit_comment'),
                path('comment/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
              ]

users/urls.py
from django.urls import path
from . import views
from django.conf import settings

app_name = 'users'
assert isinstance(settings.STATIC_URL, object)
urlpatterns = [
                path('register', views.register, name='register'),
                path('profile/<str:username>', views.profile, name='profile'),
                path('login', views.login_user, name='login'),
                path('logout', views.logout_user, name='logout'),
                path('profile/<str:username>/edit', views.edit_profile, name='editProfile'),
                path('profile/<str:username>/save', views.save, name='save')
              ]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
from django.urls import reverse


class UserExtraDetails(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="regular", max_length=50)
    gender = models.CharField(default="unknown", max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('users:profile', args=[self.user.username])


@receiver(post_save, sender=User)
def create_user_userextradetails(sender, instance, created, **kwargs):
    if created:
        UserExtraDetails.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_userextradetails(sender, instance, **kwargs):
    instance.userextradetails.save()

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from activity.models import Action
from users.models import UserExtraDetails


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        gender = request.POST.get('gender')

        try:
            user = User.objects.create_user(username, email, password)
            user.first_name = fname
            user.last_name = lname
            user.userextradetails.gender = gender
            user.save()
            messages.add_message(request, messages.SUCCESS, "Welcome " + username + "! You successfully registered!")
            request.session['username'] = username
            request.session['role'] = user.userextradetails.role
            request.session['isLoggedIn'] = 1
            return redirect('ps:homepage')
        except:
            messages.add_message(request, messages.ERROR,
                                 "Could not register user with the username: " + username + ". Please try again with a different username!")
            return redirect(request.META['HTTP_REFERER'])
    else:
        return render(request, "users/register.html")


def profile(request, username):
    user = get_object_or_404(User, username=username)
    actions = Action.objects.all().filter(user=user).order_by("-created")
    return render(request, "users/profile.html", {"user": user, "actions": actions})


def login_user(request):
    username = request.POST.get("username")
    pw = request.POST.get("pw")
    user = authenticate(username=username, password=pw)
    if user is not None:
        request.session['username'] = username
        request.session['role'] = user.userextradetails.role
        request.session['isLoggedIn'] = 1
        messages.add_message(request, messages.SUCCESS, "You have logged in successfully")
        return redirect('ps:homepage')
    else:
        messages.add_message(request, messages.ERROR, "Invalid username or password!")
        return redirect('ps:landing_page')


def logout_user(request):
    request.session.clear()
    return redirect('ps:landing_page')


def edit_profile(request, username):
    if 'isLoggedIn' in request.session and request.session['isLoggedIn'] == 1 and (
            request.session['username'] == username or request.session['role'] == 'admin'):
        user = get_object_or_404(User, username=username)
        if user is not None:
            return render(request, "users/edit-profile.html", {"user": user})
        else:
            messages.add_message(request, messages.ERROR, "The user you are trying to edit is invalid: " + username)
    else:
        messages.add_message(request, messages.ERROR,
                             "Unauthorised to edit " + username + "! Please login with appropriate credentials")
    try:
        return redirect(request.META['HTTP_REFERER'])
    except:
        return redirect('ps:landing_page')


def save(request, username):
    if 'isLoggedIn' in request.session and request.session['isLoggedIn'] == 1 and (
            request.session['username'] == username or request.session['role'] == 'admin'):

        user = get_object_or_404(User, username=username)
        if 'email' in request.POST and request.POST.get('email') != '':
            user.email = request.POST.get('email')

        if 'password' in request.POST and request.POST.get('password') != '':
            user.password = request.POST.get('password')

        if 'fname' in request.POST and request.POST.get('fname') != '':
            user.first_name = request.POST.get('fname')

        if 'lname' in request.POST and request.POST.get('lname') != '':
            user.last_name = request.POST.get('lname')

        if 'gender' in request.POST and request.POST.get('gender') != '':
            user.userextradetails.gender = request.POST.get('gender')

        if request.session['role'] == 'admin' and 'role' in request.POST and request.POST.get('role') != '':
            user.userextradetails.role = request.POST.get('role')
            action = Action(
                user=get_object_or_404(User, username=request.session['username']),
                verb="changed role to " + request.POST.get('role') + "for user: ",
                target=user
            )
            action.save()

        user.save()
        messages.add_message(request, messages.SUCCESS,
                             "Profile for " + username + " updated successfully!")
    else:
        messages.add_message(request, messages.ERROR,
                             "Unable to update the profile for " + username + ". Please login with valid credentials")

    return redirect(request.META['HTTP_REFERER'])

templates/users/edit-profile.html
<!-- Add view, Edit view, Delete view
This page displays the form in which is used to view, add, edit and delete the plant listing.
       Delete functionality is only visible to logged in user with role: admin in edit view
 -->
{% extends "../plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <script src="{% static "css/profile.css" %}"></script>
{% endblock %}

{% block primary-navigation %}
    <li><a href="/plant-sharing">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
{% endblock %}
{% block content %}
    <div id="profile">
        <h3>Profile for {{ user.username }}</h3>
        <p>* = required</p>
        <div id="registration">
            <form action="{% url 'users:save' user.username %}" class="register" method="POST">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" name="username" required disabled value="{{ user.username }}">
                <br>
                <label for="password">Password:</label>
                <input type="password" name="password" maxlength="20" minlength="4">
                <br>
                <label for="email">Email:</label>
                <input type="email" name="email" value="{{ user.email }}">
                <br>
                <label for="fname">First name:</label>
                <input type="text" name="fname" maxlength="20" minlength="4"  value="{{ user.first_name }}">
                <br>
                <label for="lname">Last name:</label>
                <input type="text" name="lname" maxlength="20" minlength="4"  value="{{ user.last_name }}">
                <br>
                <label for="gender" >Gender:</label>
                <input type="radio" name="gender" value="male"  {% if user.userextradetails.gender == 'male'  %} checked {% endif %} required>Male
                <input type="radio" name="gender" value="female" {% if user.userextradetails.gender == 'female'  %} checked {% endif %} >Female
                <input type="radio" name="gender" value="other" {% if user.userextradetails.gender == 'other'  %} checked {% endif %} >Other
                <br>
                {% if request.session.role == 'admin' %}
                    <label for="role">Role:</label>
                    <select name="role">
                        <option value="admin" {% if user.userextradetails.role == 'admin'  %} selected {% endif %}>Admin</option>
                        <option value="regular" {% if user.userextradetails.role == 'regular'  %} selected {% endif %}>Regular</option>
                    </select>
                    <br>
                {% endif %}
                <input type="submit" value="Save">
            </form>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
<!-- Add view, Edit view, Delete view
This page displays the form in which is used to view, add, edit and delete the plant listing.
       Delete functionality is only visible to logged in user with role: admin in edit view
 -->
{% extends "../plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <script src="{% static "css/profile.css" %}"></script>
{% endblock %}

{% block primary-navigation %}
    <li><a href="/plant-sharing">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
{% endblock %}
{% block content %}
    <div id="profile">
        <h3>Profile for {{ user.username }}</h3>
        <p>* = required</p>
        <dl>
            <dt>Username:</dt>
            <dd>{{ user.username }}</dd>

            <dt>Role:</dt>
            <dd>{{ user.userextradetails.role }}</dd>

            <dt>FirstName:</dt>
            <dd>{{ user.first_name }}</dd>

            <dt>LastName:</dt>
            <dd>{{ user.last_name }}</dd>

            <dt>Email:</dt>
            <dd>{{ user.email }}</dd>

            <dt>Gender:</dt>
            <dd>{{ user.userextradetails.gender }}</dd>

        </dl>
        {% if request.session.role == 'admin' or request.session.username == user.username %}
            <form action="{% url 'users:editProfile' user.username %}" class="register" method="GET">
                {% csrf_token %}
                <input type="submit" value="Click to Edit Profile">
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block sidebar %}
    {% include "actions/action/feed.html" %}
{% endblock %}

templates/users/register.html
<!-- Add view, Edit view, Delete view
This page displays the form in which is used to view, add, edit and delete the plant listing.
       Delete functionality is only visible to logged in user with role: admin in edit view
 -->
{% extends "../plant-sharing/base.html" %}
{% load static %}
{% block page-title %}Plants Listings{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{% static "css/logged-in.css" %}">
    <link rel="stylesheet" href="{% static "css/register.css" %}">
{% endblock %}

{% block extrascripts %}
    <script src="{% static "js/plantdetails.js" %}"></script>
{% endblock %}
{% block primary-navigation %}
    <li><a href="/plant-sharing">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Blogs</a></li>
{% endblock %}
{% block content %}
    <div id="registration">
        <h3>Please enter the details below to register:</h3>
        <p>* = required</p>
        <form action="{% url 'users:register' %}" class="register" method="POST">
            {% csrf_token %}
            <label for="username">Username:*</label>
            <input type="text" id="username" name="username" required maxlength="20" minlength="4">
            <br>
            <label for="password">Password:*</label>
            <input type="password" id="password" name="password" required maxlength="20" minlength="4">
            <br>
            <label for="email">Email:*</label>
            <input type="email" id="email" name="email" required>
            <br>
            <label for="fname">First name:*</label>
            <input type="text" id="fname" name="fname" required maxlength="20" minlength="4">
            <br>
            <label for="lname">Last name:*</label>
            <input type="text" id="lname" name="lname" required maxlength="20" minlength="4">
            <br>
            <label for="gender">Gender:*</label>
            <input type="radio" name="gender" value="male" checked required>Male
            <input type="radio" name="gender" value="female">Female
            <input type="radio" name="gender" value="other">Other
            <br>
            <input type="submit" value="Register">
            <br>Already registered? <a href="{% url 'ps:landing_page' %}">Sign in</a>
        </form>
    </div>
{% endblock %}